apiVersion: v1
kind: Secret
metadata:
  name: saas-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.secrets.dbUser }}"
  DB_PASSWORD: "{{ .Values.secrets.dbPassword }}"
  JWT_SECRET: "{{ .Values.secrets.jwtSecret }}"
